name: refresh-calendar-access

on:
  workflow_dispatch:

jobs:
  gen-auth-token:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'actions/setup-python@v4'
      with:
        python-version: '3.11'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
#        project_id: 'website-calendar-415211'
        workload_identity_provider: 'projects/604298549901/locations/global/workloadIdentityPools/github/providers/kyleaoman-github-io'
        service_account: 'calendar-service-account@website-calendar-415211.iam.gserviceaccount.com'
        access_token_lifetime: '300s'
    - run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
        echo '${{ steps.auth.output.auth_token }}'
        python refresh_calendar.py '${{ steps.auth.output.auth_token }}'
#    - run: |-
#       curl -H 'Bearer: ${{ steps.auth.outputs.auth_token }}' https://calendar.google.com/calendar/embed?src=kyleaoman%40gmail.com&ctz=Europe%2FLondon
    
