name: refresh-calendar-access

on:
  workflow_dispatch:

jobs:
  refresh-calendar-access:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'actions/setup-python@v4'
      with:
        python-version: '3.11'
    - name: 'Refresh calendar access'
    - run: |
        python refresh_calendar.py
	git config --global user.name 'CalendarBot' && git config --global user.email 'kyleaomanusers.noreply.github.com' && git commit -a -m 'Refresh calendar embedding info.' && git push
