name: refresh-calendar-access

on:
  workflow_dispatch:

jobs:
  refresh-calendar-access:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Update calendar embedding info.
      CI_COMMIT_AUTHOR: Calendar Bot
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'actions/setup-python@v4'
      with:
        python-version: '3.11'
    - name: 'Refresh calendar access'
      run: |
        python refresh_calendar.py
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "kyleaoman@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
